_target_: pytorch_lightning.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_epochs: 20
max_steps: 100000
log_every_n_steps: 10
num_sanity_val_steps: 0

accelerator: gpu
devices: [3]

# mixed precision for extra speed-up
precision: 32
gradient_clip_val: 0

# perform a validation loop every N training epochs
val_check_interval: 1.0

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

# meta-batch-size
accumulate_grad_batches: 1
