# @package _global_

defaults:
  - _self_
  - data: domainnet_infograph_contrastive.yaml
  - model: prompt_tta_ViT_B16_CLIP.yaml
  - logger: tensorboard.yaml
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: "./default"
seed: 42